LDLIBS = -lncurses -ltinfo
CFLAGS = -ggdb3 -O0
CPPFLAGS = -W -Wall -Wno-missing-field-initializers -Wno-sign-compare -Wno-unused-parameter -Wno-pointer-sign
.PHONY: clean

all: keymap

clean:
	$(RM) *.o keymap
